### ISSUE TITLE
Minecraft java requires new JDK version 

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/gamesvr-minecraft#9]
I was getting an error saying this version of the java runtime only recognizes class file versions up to a certian version. The fix was use this guide to update java . This needs to be implemented in docker. 

https://www.linuxcapable.com/how-to-install-java-17-lts-jdk-17-on-ubuntu-20-04/

**Comment by dudleycodes** [comment]
The Dockerfile is already using Java 17 - there isn't a new version.

Closing this issues because there's no way you had it with the Dockerfiles provided in this repo. If you did somehow have this issue with this issue, comment w/ exact error message / conditions and we can reopen.
